/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_control4_yamba_yambaservice_YambaLib */

#ifndef _Included_com_control4_yamba_yambaservice_YambaLib
#define _Included_com_control4_yamba_yambaservice_YambaLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_control4_yamba_yambaservice_YambaLib
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_control4_yamba_yambaservice_YambaLib_log
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
